name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, test, and build
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        CI: true
        name: CI
    - name: Deploy the build
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'build/'
        dest: ${{ secrets.DEPLOY_DESTINATION }}
    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
